### ISSUE TITLE
Error out of context: "Enter an amount of STX" 

### ISSUE THREAD

**Issue by pors** [hirosystems/stacks-wallet#1003]
During a smart contract call that transfers some amount I got this message:

<img width="762" alt="Screenshot 2021-12-10 at 10 09 34" src="https://user-images.githubusercontent.com/1078320/145628968-ab8fc966-d2c4-4c64-a429-9e81ee810fd8.png">

The error doesn't make sense as the amount is set by the application, not through user input directly.
Also there is no input field to enter an amount anyway.

This error occurred on the [lnswap.org](https://lnswap.org) application.

I suspect that it can be reproduced as follows: 
- initiate a swap from BTC => STX
- add a STX amount that is above the maximum (enforced by a post-condition)
- follow the steps in the app.

**Comment by fbwoolf** [comment]
Were you intending to open this issue in the web wallet? This repo is for the desktop wallet.

**Comment by pors** [comment]
Oops, sorry. Yes for the web wallet.

**Comment by pors** [comment]
Moving to web wallet
