### ISSUE TITLE
[4.6.0] Bug: <describe issue>

### ISSUE THREAD

**Issue by crokeefe** [hirosystems/stacks-wallet#1011]
![Stacks-Kuc-to-Hiro-web-wallet-staking-2](https://user-images.githubusercontent.com/37124928/147001681-5399a3dd-c8a0-445a-8f29-9b8040eb5af9.PNG)
![Stacks-Kuc-to-Hiro-web-wallet-staking-3](https://user-images.githubusercontent.com/37124928/147001684-19a1b2d0-9364-46a2-bb29-b2ae28e6f858.PNG)
![Stacks-Kuc-to-Hiro-web-wallet-staking-0](https://user-images.githubusercontent.com/37124928/147001685-bd9a79ae-c2a1-427e-a40d-0f185943ced8.PNG)
![Stacks-Kuc-to-Hiro-web-wallet-staking-1](https://user-images.githubusercontent.com/37124928/147001686-3edf021c-a1b7-4494-a4e6-2200cd2abadd.PNG)

Bug found testing Hiro Wallet build undefined, 4.6.0.  // Web wallet v2.23.2 and desktop

I made my wallet and now cannot find it on the explorer. 
I've also sent STX to it from Kucoin and now it's just pending. Maybe bc the address isn't real?

**Comment by crokeefe** [comment]
SP3JBRVDPYES4PDQANQGJ6V9N4Q74SFE96TYP59Y9

**Comment by crokeefe** [comment]
OK, the addr is on the explorer now. I will ping Kucoin to see if they can try again.

**Comment by fbwoolf** [comment]
Since this is resolved for you in the explorer, I will close this issue. We do have another issue created to provide better feedback to the user in this situation: https://github.com/hirosystems/explorer/issues/544

**Comment by crokeefe** [comment]
Now my addr is no longer on the explorer.
error: "No principal found with address SP3JBRVDPYES4PDQANQGJ6V9N4Q74SFE96TYP59Y9"

**Comment by fbwoolf** [comment]
Bc the information is going in/out, this is likely an api issue not an explorer issue. We are just displaying the data the api provides. There have been api issues being worked on over the past few days. You can follow along in the #api channel on Discord.
