### ISSUE TITLE
[4.6.1] Bug: Sent some STX to my Hiro account - gone missing

### ISSUE THREAD

**Issue by Marcus2TTP** [hirosystems/stacks-wallet#1014]
Bug found testing Hiro Wallet build undefined, 4.6.1.
![image](https://user-images.githubusercontent.com/96814564/147638780-b3b340c2-1d8b-496f-9aec-4542065771a8.png)

![image](https://user-images.githubusercontent.com/96814564/147638817-7e31ae22-c10a-4c21-904e-e2b79d47c950.png)

**Comment by kyranjamie** [comment]
This was either a temporary API issue, or an issue with the exchange's withdrawal. Please either follow up with the exchange,  or more info for us to troubleshoot.
