### ISSUE TITLE
[4.6.1] Bug: Hiro tries to connect to Sentry despite diagnostics being turned off

### ISSUE THREAD

**Issue by skibitsky** [hirosystems/stacks-wallet#1015]
Hiro on macOS tries to connect to Sentry despite diagnostics being turned off.
During initial Hiro launch I refused to provide any analytics data. After having Hiro running in the background for more than 1h, it tried to connect to Sentry, error tracking software. 

Bug found testing Hiro Wallet build undefined, 4.6.1.

<img width="1084" alt="Gleb's Screenshot 2022-01-05 at 15 46 24@2x" src="https://user-images.githubusercontent.com/15127974/148228408-ce47b11f-9bb3-42af-aa9d-82b524068506.png">

**Comment by kyranjamie** [comment]
Thanks for reporting @skibitsky, indeed this shouldn't happen. 

We have a check on all sentry log actions to prevent sharing data from wallets that haven't given permission.

https://github.com/hirosystems/stacks-wallet/blob/0086913ebd927c95fb9f88fc5d6a54b2c0544c30/app/main/register-sentry-state-listener.ts#L7-L13

We'll investigate.

**Comment by He1DAr** [comment]
> We should resolve this ASAP. @He1DAr have you been able to take a look yet by chance?

Just started looking into it, will give an update once the cause is identified.
