### ISSUE TITLE
[4.6.1] Bug: Public key mismatch. Make sure you're using the same Ledger you created the wallet with.

### ISSUE THREAD

**Issue by raymonddurk** [hirosystems/stacks-wallet#1018]
I plugged in the same Ledger as I normally do to revoke delegation for an expired pool and got the message "Public key mismatch. Make sure you're using the same Ledger you created the wallet with." as seen below. It is the same ledger, same seed, nothing has changed over the last few months other than a firmware update to the latest software.

![image](https://user-images.githubusercontent.com/8037263/148864570-77ffae03-60b7-47bf-970d-2ef18eb55eff.png)

Bug found testing Hiro Wallet build undefined, 4.6.1.

**Comment by kyranjamie** [comment]
If you reset your wallet `Settings > Reset Wallet` and restore from your Ledger, do you get back to the address you expect?

This error should only show if, as stated, the public keys differ.

**Comment by raymonddurk** [comment]
When I reset the wallet and use the Ledger the wallet appears empty. Like I said, the only change to the ledger was updated firmware. I never re-entered the recovery phrase or a pass phrase during the update since the delegation began. It should return the same pubkey from the same device.

**Comment by kyranjamie** [comment]
I have a Ledger on firmware `v2` which I just upgraded to `v2.1`. It resolves the same key for me. Did you ever use the passphrase feature of the Ledger?

**Comment by raymonddurk** [comment]
OMG I am so sorry. That was it. I literally never use a Ledger except for this and when you said that I thought, "Hiro doesn't have passphrases" then remembered Ledger is like a Coldcard and not a Trezor in that manner. I literally spent the weekend looking for old screenshots of derivation paths.
