### ISSUE TITLE
[4.6.1] Bug: Failed tx NotEnoughFunds

### ISSUE THREAD

**Issue by kbahrani7** [hirosystems/stacks-wallet#1037]
![Screen Shot 2022-02-06 at 5 21 53 PM](https://user-images.githubusercontent.com/78942162/152703955-1025d1e4-9259-4a82-9999-6f12f3ecc919.png)

Bug found testing Hiro Wallet build undefined, 4.6.1.

**Comment by kbahrani7** [comment]
I have even left 4 stx and it still fails...

**Comment by fbwoolf** [comment]
This is not a bug in our wallet, this is a response from the api ...reason indicates there are not enough funds?

**Comment by kbahrani7** [comment]
I have over 500 STX...

**Comment by kbahrani7** [comment]
SP2V0SER5EAT5CDYH18JDB873VWBTXQ3GGQRNDTV2
Now I'm delegating because I did not know how long until I'd get a response, but you can look up my address. I am using the ledger with it as well if that helps...I can't believe it's looking like my STX will be stuck on here permanently :/
![Screen Shot 2022-02-06 at 5 55 18 PM](https://user-images.githubusercontent.com/78942162/152705026-9f8a8154-3940-434f-9371-52790c281b4c.png)

**Comment by kbahrani7** [comment]
I can revoke my STX, but any suggestions or ideas of why this is happening??

**Comment by fbwoolf** [comment]
Not too sure yet but can look into it. If you are using Ledger then this issue should be reported in the desktop wallet repo, so I'll transfer it there. This is for the web wallet.

**Comment by fbwoolf** [comment]
Nvm, I thought this was in the web wallet ...disregard previous comment.

**Comment by kbahrani7** [comment]
It's fixed!! I think I needed to just restart the app after the transaction failed...TY for your fast responses!! :)

**Comment by fbwoolf** [comment]
> It's fixed!! I think I needed to just restart the app after the transaction failed...TY for your fast responses!! :)

Fantastic, np!
