### ISSUE TITLE
What is the license of this software?

### ISSUE THREAD

**Issue by neoxian** [hirosystems/stacks-wallet#1043]
Please add License file stating license of this app.  GPL? MIT?  something else?

Thank you.

**Comment by kyranjamie** [comment]
It's licenced under GPLv3

**Comment by raymonddurk** [comment]
Can you add that then so other people can fork it and develop on it without hesitation of being sued

![image](https://user-images.githubusercontent.com/8037263/154131314-9eebc810-d5dd-45de-915e-d6e1da702fe5.png)
