### ISSUE TITLE
[4.6.1] Bug: <describe issue>  my password don't work from my Hiro Wallet

### ISSUE THREAD

**Issue by LukeDesch** [hirosystems/stacks-wallet#1046]
Bug found testing Hiro Wallet build undefined, 4.6.1.

**Comment by unclemantis** [comment]
Did this issue start after you installed 4.6.1? Have you checked if the CAPS-LOCK is active? Do you have access to your 24 word secret phrase?


> 
> 
> Bug found testing Hiro Wallet build undefined, 4.6.1.
> 
>

**Comment by LukeDesch** [comment]
Yes, i have the 24 word

**Comment by kyranjamie** [comment]
If you have your seed phrase, and your password doesn't work, you can reset and restore your wallet from the words.
