### ISSUE TITLE
[4.6.1] Functionality to create a new wallet on Ledger, or input previously created seed

### ISSUE THREAD

**Issue by pleblira** [hirosystems/stacks-wallet#1047]
Hi! Question about using Ledger Nano X with Hiro. 

Is there a way to use my own 24-word seed phrase with Ledger, or does it only have one predefined seed? 

On the Hiro desktop app, regardless of whether I choose 'Create a New Wallet' or 'I Already Have a Wallet', if I use the Ledger I will always get the same wallet address out of it, to which I don't have the seed words for. Or do I? It wouldn't be using the seed from my BTC wallet, right? I don't know if these would be interconnected...

From what I'm seeing, the Ledger can only generate a single wallet address, and there isn't a way to get access to the seed phrase for this address.

I'm looking to move some STX to this Ledger and would like to have the seed words backed up in case the Ledger breaks or I lose it, and ideally create the wallet on an offline computer.

Don't know if this functionality hasn't been developed yet, or maybe I'm missing something really obvious.
Thanks so much in advance!

**Comment by kyranjamie** [comment]
> Is there a way to use my own 24-word seed phrase with Ledger, or does it only have one predefined seed?

It is possible to restore any seed phrase on a Ledger, but this defeats the point. The idea is that the key never leaves the device.

> to which I don't have the seed words for

You should have saved your seed phrase when you set up your Ledger. If you don't have it, I recommend transferring all your funds off the device immediately, and set up the device again, this time writing down the seed phrase.

> the Ledger can only generate a single wallet address, and there isn't a way to get access to the seed phrase for this address.

The Ledger doesn't create new seed phrases for every address. A Ledger just has 1 seed phrase.

Hope this helps, though as this relates to the functionality of the Ledger, not the wallet, I'll close this issue.
