### ISSUE TITLE
Issue with adding Stacks app on Ledger Live and accessing Hiro wallet

### ISSUE THREAD

**Issue by shaktistacks** [hirosystems/stacks-wallet#1055]
There's a new Firmware update to 2.0.2 for Ledger at noon and after that I'm unable to reinstall the Stacks App on ledger live that allows accessing the Hiro Wallet on Desktop(attached screenshots). please advise the steps for fixing this.

![image](https://user-images.githubusercontent.com/93597797/156447536-ea178c38-a534-46f0-a903-9d2ed2c6c17d.png)
![image](https://user-images.githubusercontent.com/93597797/156447574-b7106a66-c605-43ea-8902-7433a6a83e63.png)

**Comment by fbwoolf** [comment]
Do you have 'Developer Mode' turned on? Check the instructions here under `How can I use my Ledger device with the Hiro Wallet?`: https://www.hiro.so/wallet#download

**Comment by shaktistacks** [comment]
Thanks !! i forgot that i've to enable the dev mode again after update! it works !!
