### ISSUE TITLE
Does anyone know about this bug help me

### ISSUE THREAD

**Issue by Awol214** [hirosystems/stacks-wallet#1059]
Here is the issue I enter my seedphrase correctly but it always says it's wrong is it capitalization or it's really a bug 
![Screenshot_20220317_140731](https://user-images.githubusercontent.com/101788451/158748008-5dc30324-d256-40c5-96ee-38200e4e8049.jpg)

**Comment by markmhx** [comment]
You appear to be using the Ronin Wallet, which is a separate project.
