### ISSUE TITLE
[4.6.1] Bug: <describe issue>

### ISSUE THREAD

**Issue by CapdeCabo** [hirosystems/stacks-wallet#1064]
I am trying to create a wallet using my ledger. The instructions require me to open the Stacks app, but I cannot find it on the ledger app manager to download. A secondary issue, ledger live doesn't seem to work with the Hiro wallet open.

Bug found testing Hiro Wallet build undefined, 4.6.1.

**Comment by unclemantis** [comment]
I somewhat recall the need to activate ether debug or develop mode in LIVE

> I am trying to create a wallet using my ledger. The instructions require me to open the Stacks app, but I cannot find it on the ledger app manager to download. A secondary issue, ledger live doesn't seem to work with the Hiro wallet open.
> Bug found testing Hiro Wallet build undefined, 4.6.1.

**Comment by kyranjamie** [comment]
Thanks for helping with support @unclemantis. Indeed, you'll need to enable developer mode, while we wait for Ledger to do their final code review (1.5years+ in the waiting).

LL not working with the Hiro Wallet open is expected, unfortunately. Only one app can interact with the USB at once

**Comment by CapdeCabo** [comment]
Thank you all. I'm not a developer, so might wait a little longer.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
