### ISSUE TITLE
[4.6.1] Bug: SENDing STX generates no result

### ISSUE THREAD

**Issue by divine-wind** [hirosystems/stacks-wallet#1094]
I have thrice used the SEND function of Hiro Wallet v4.6.1 on macOS 12.4. It generates no result, but also no error code and no confirmation. After entering the password in the app, the action is pending for a couple of seconds, then it appears to finish, but the Transaction history shows nothing.

Bug found testing Hiro Wallet build undefined, 4.6.1.

**Comment by markmhx** [comment]
Mind sending a screenshot of your wallet's home screen, with any personal information removed?

**Comment by divine-wind** [comment]
Hi there,

Yes, see attached screenshot.

[image: image.png]

Cheers,

Jakob

**Comment by divine-wind** [comment]
![mail](https://user-images.githubusercontent.com/84845646/176965584-2d7c2e62-fab4-4379-b37f-194a1a3b87ec.png)

**Comment by divine-wind** [comment]
Initially, there were no signs of the transaction in the app, even after restarting it.

However, the transaction later on became visible in the app. 

It appears then that the bug is not with the transaction itself within the app, but with the UI completely hiding it when it is pending. I believe that is what needs to be resolved.

Best.
