### ISSUE TITLE
Fix typo in stacking flow (buffer warning)

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/stacks-wallet#1109]
![image](https://user-images.githubusercontent.com/33360391/201046133-b6b483b2-0452-4bdf-a1e6-ac1eb66a45ce.png)

**Comment by edu-stx** [comment]
I'm a little puzzled by this issue: [the text was last changed ~2 years ago](https://github.com/hirosystems/stacks-wallet/blame/dev/app/pages/stacking/direct-stacking/components/choose-direct-stacking-amount.tsx#L74) with the correct spelling, "chance". I also just downloaded the wallet and it too has the correct spelling, so not sure how I can reproduce this?

![image](https://user-images.githubusercontent.com/116000646/206462484-5cc7edde-f3f8-459f-aa1c-a51b06d3c318.png)

**Comment by edu-stx** [comment]
When comparing the two screenshots, the text styling is different in some areas, so perhaps the first screenshot is from a different version. I'm using the latest available for linux, `stacks-wallet.mainnet.v4.6.1.deb`.

Did notice a different typo though, there's a missing space paragraph 2 line 2: `cycle.If` should be `cycle. If`.

**Comment by edu-stx** [comment]
@314159265359879 what version were you on when you reported the issue? Is it still happening with the latest version?

**Comment by 314159265359879** [comment]
Yes this looks resolved, good find on the other typo! Testnet wallet is always showing:
![image](https://user-images.githubusercontent.com/33360391/206479660-76384cbc-5a80-46a3-82e7-fa87fb8b66b5.png)
so I may have been on an old version. At the time I was also going through the flows on Figma, and the typo is in there, the screenshot from there would also explain the difference in styling difference. I will make sure to double check version next time.
