### ISSUE TITLE
Wrong wallet address

### ISSUE THREAD

**Issue by jeffmail** [hirosystems/stacks-wallet#1115]
Tonight I had the same thing happen. Has anyone ever seen or fixed this?

For the last year my stx wallet was:
SPCGY4K9AN72MBEX51DYX72R7RMV9NQ3X59MNSZQ

I have some NFTs, domain name, and 1000 STX.

Today after several months I signed back into my hiro wallet with my secret key which I have always used and store in a physical safe. It let me restore wallet by entering secret but it gave me this address:
SP1JY8YPH63GV1FDM2YBKY3F2BM75QQBCW0603PTS

I dont see my other address or tokens/etc. When I look for additional accounts it did not show any. I clicked new account and it creates new addresses, but I dont have my old one.

When I look on stx blockchain, I can find my old address and tokens/etc, but if I try and search for this new wallet address it just says no wallet found. Can anyone help?

I just tried with the xverse mobile app and still have the same issue, previously I tried with the hiro web wallet (chrome).

I am having the same issues described in this post
https://github.com/hirosystems/stacks-wallet/issues/830

[4.3.0] Bug: Wrong wallet address #830

**Comment by 314159265359879** [comment]
Hi @jeffmail, 

I am very sorry you are having this issue. Do I understand correctly you are using the Hiro Wallet in the browser (Web extension)? 

When you are shown different public address the only scenario is that you are using a different seed phrase. The same seed phrase will always produce the same public address(es). 
What has happened to users in the past is that they mistakenly used the seed for their Bitcoin wallet to access their Stacks account. Since these are compatible that is possible. Do you have any other seeds you can check?

**Comment by jeffmail** [comment]
> Hi @jeffmail,
> 
> I am very sorry you are having this issue. Do I understand correctly you are using the Hiro Wallet in the browser (Web extension)?
> 
> When you are shown different public address the only likely scenario is that you are using a different seed phrase. The same seed phrase will always produce the same public address(es). What has happened to users in the past is that they mistakenly used the seed for their Bitcoin wallet to access their Stacks account. Since these are compatible that is possible. Do you have any other seeds you can check?

I think the issue is I am getting a second (non principle wallet address shown in the hiro wallet. The seed phase had a primary wallet SPCGY4K9AN72MBEX51DYX72R7RMV9NQ3X59MNSZQ

and a secondary wallet (create additional account)
SP1JY8YPH63GV1FDM2YBKY3F2BM75QQBCW0603PTS

when I log in now I only see the non-principle
SP1JY8YPH63GV1FDM2YBKY3F2BM75QQBCW0603PTS

if I search the stx explorer for SP1JY8YPH63GV1FDM2YBKY3F2BM75QQBCW0603PTS, it gives me an error telling its not a principle wallet address, but in my hiro it shows as account 1 and the previous account 1 does not show.  The seed phase was stored written in my safe and I was able to log into it many times over the last year, this is a brand new issue. I have been using crypto since 2013 and I am certain this isnt a seed phase mistake.

the primary principle disappeared.
![hiro_Capture](https://user-images.githubusercontent.com/34929020/202724083-6af7cdde-8a73-4542-927e-d12c341a66ee.PNG)

**Comment by jeffmail** [comment]
I used to have 2 other accounts in there, the primary and another non primary. they both had .btc domains, not sure if that's relative

**Comment by 314159265359879** [comment]
> I used to have 2 other accounts in there, the primary and another non primary. they both had .btc domains, not sure if that's relative

Yes this is helpful. This can help us troubleshoot. Would you mind sharing the names? If you prefer to keep then private please email me at wallet at hiro.so

**Comment by 314159265359879** [comment]
It turned out that a different key had been input than expected. Closing this as solved.
