### ISSUE TITLE
Fix analytics in production

### ISSUE THREAD

**Issue by markmhx** [hirosystems/stacks-wallet#1117]
For some reason, events are not getting sent to Segment in general for the desktop wallet in production; however, they appear to work in dev and staging. This consists of investigating and resolving why they're broken.

**Comment by edu-stx** [comment]
After some investigating, I couldn't find anything obvious in the code that required fixing. It may just be a misconfigured github secret (I don't have access to them).

Just in case, I've updated the segment lib in https://github.com/hirosystems/stacks-wallet/pull/1134 , which itself is waiting for https://github.com/hirosystems/stacks-wallet/pull/1133 to be merged first.

**Comment by edu-stx** [comment]
I'm prepared to merge PR with the updated Segment lib. To be sure we've covered all cases, we should confirm that Segment's write key, defined in GH secrets as `SEGMENT_WRITE_KEY`, matches is set to the [prod desktop wallet](https://app.segment.com/hirosystems/sources/stacks-desktop-wallet/settings/keys).

I don't have access to secrets. @kyranjamie @markmhx is this something you could take a look at or grant me access to do myself?

**Comment by kyranjamie** [comment]
Done @edu-stx

**Comment by edu-stx** [comment]
@markmhx seeing events show up again, seems to be fixed now.
