### ISSUE TITLE
[4.6.1] Update hiro.so wallet download link to latest version (automatically)

### ISSUE THREAD

**Issue by aamjad2001** [hirosystems/stacks-wallet#1130]
Bug found testing Hiro Wallet build undefined, 4.6.1.
I have updated to desktop version 4.6.1 but even after update its still showing "Update available" on the top

**Comment by 314159265359879** [comment]
Thanks for reporting @aamjad2001 we'll want to fix this so the "update available" message is only displayed when there is a new version available.

**Comment by 314159265359879** [comment]
> Thanks for the report @aamjad2001, are you having the same issue with the [latest release](https://github.com/hirosystems/stacks-wallet/releases)? I'm unable to reproduce.

Thanks to cubricray on Telegram, I now see the issue isn't with the wallet. [The hiro.so webpage](https://wallet.hiro.so/wallet/install-desktop) is directing to 4.6.1 even now. We'll need to update that. Should that be automatic with a release?

![image](https://user-images.githubusercontent.com/33360391/209486486-531b0a94-e6fd-4199-8fcc-f5fe7e7972b4.png)

**Comment by markmhx** [comment]
Let's hold off on fixing this until https://github.com/hirosystems/stacks-wallet/issues/1139 is resolved since the latest version has a critical Ledger bug coincidentally.

**Comment by 314159265359879** [comment]
#1139 is resolved, good time for this one. The Hiro.so site is still pointing to 4.6.1.

**Comment by markmhx** [comment]
Let's resolve https://github.com/hirosystems/stacks-wallet/issues/1149 as well before tackling this one

**Comment by markmhx** [comment]
We can move forward with the website fix here now since we've discovered that #1149 is due to an API-borne issue, not wallet-borne.

**Comment by tprebz** [comment]
The website is fixed, and the script to auto-update the download links based on latest release is alive once again.
