### ISSUE TITLE
Unable to connect with ledger using 4.7.0 "A JavaScript error occurred in the main process" on Windows

### ISSUE THREAD

**Issue by 314159265359879** [hirosystems/stacks-wallet#1139]
See error when asked to connect ledger:

![image](https://user-images.githubusercontent.com/33360391/210110834-de660093-0e47-42ce-8aff-508401c960f0.png)

After uninstalling 4.7.0, and going back to installing 4.6.1 then connecting Ledger went without issue. A consecutive upgrade to 4.7.0 resulted in the issue coming up again as soon as I tried to connect with Ledger:
![image](https://user-images.githubusercontent.com/33360391/210110898-cb7233c2-82d4-4580-8ceb-3fef41e27e28.png)

I have not seen other reports of this bug yet but that could be because users are still using 4.6.1 because of the [redirect issue](https://github.com/hirosystems/stacks-wallet/issues/1130). I am assuming this is broken for everyone using the desktop wallet (on Windows) with Ledger. We can change this to P2 if this issue proves less general.

**Comment by markmhx** [comment]
@edu-stx @kyranjamie which of you prefers to tackle this one?

**Comment by edu-stx** [comment]
Unable to reproduce in latest build. Was able to sign in using a Ledger device,

![screenshot](https://user-images.githubusercontent.com/116000646/210829310-cc5a03ee-ef5a-4d4a-b841-09f2a8fe387f.png)

Suggest we close for now.

**Comment by markmhx** [comment]
@edu-stx this is fixed in the next release? or you weren't able to recreate?

**Comment by edu-stx** [comment]
I'm inclined to believe that it is fixed as I wasn't able to recreate. I didn't take any specific actions to address this issue, although I wouldn't be surprised if it got resolved as a result of updating several packages in preparation for [4.8.0](https://github.com/hirosystems/stacks-wallet/releases/tag/v4.8.0).

If it comes up again, we can re-open the issue and investigate further.

**Comment by markmhx** [comment]
@314159265359879 Mind using v4.8.0 to see if you can recreate on your end?

**Comment by 314159265359879** [comment]
> @314159265359879 Mind using v4.8.0 to see if you can recreate on your end?

Tested, looking good, issue resolved. 

Lets take care of https://github.com/hirosystems/stacks-wallet/issues/1130 now ;-)

**Comment by markmhx** [comment]
Great! I'm thinking we may want to resolve https://github.com/hirosystems/stacks-wallet/issues/1149 before #1130
