### ISSUE TITLE
[4.8.0] Bug: After updating my Hiro Wallet, my pool amount now shows 0 STX, but my locked amount stayed the same. I also updated my Ledger Nano X Stacks app before I did the Hiro Wallet update. 

### ISSUE THREAD

**Issue by Hammer187** [hirosystems/stacks-wallet#1151]
Bug found testing Hiro Wallet build undefined, 4.8.0.

 After updating my Hiro Wallet, my pool amount now shows 0 STX, but my locked amount stayed the same. I also updated my Ledger Nano X Stacks app before I did the Hiro Wallet update. I think it could be a visual bug with the desktop app because my stacked amount on the explorer shows correctly. 

![image](https://user-images.githubusercontent.com/79030083/212480785-389cb9bc-7a00-4801-9b69-e6008cd23afc.png)

Windows 10 Build 19045

**Comment by markmhx** [comment]
Closing this issue out since we'll continue tracking the issue on #1149 and https://github.com/hirosystems/stacks-blockchain-api/issues/1520
