### ISSUE TITLE
[4.8.0] Bug: Staking not progressing

### ISSUE THREAD

**Issue by FrCrypt00** [hirosystems/stacks-wallet#1159]
Bug found testing Hiro Wallet build undefined, 4.8.0.

**Comment by markmhx** [comment]
Mind sharing a screenshot?

**Comment by FrCrypt00** [comment]
![stx](https://user-images.githubusercontent.com/118445082/221512072-e9c8ceca-39a9-4bf8-a203-a188ce47bef7.PNG)

**Comment by 314159265359879** [comment]
Thanks for sharing @FrCrypt00 this is a known issue and we are working on a fix. We expect it in the next version of the Desktop Wallet: 
Some more details; https://github.com/hirosystems/stacks-wallet/issues/1155#issuecomment-1407062520

**Comment by FrCrypt00** [comment]
Ok, Thank you. I'll wait for tue next version
