### ISSUE TITLE
[4.1.2] Bug: Validation error thrown despite valid Stack address and amount

### ISSUE THREAD

**Issue by Eshwari007** [hirosystems/stacks-wallet#757]
Bug found testing Stacks Wallet build undefined, 4.1.2.

Environment:
TestNet

Actual results:
User was testing the Stack address with an amount while writing up a Memo.
User selected the Preview button and reviewed the data
User then went back to the initial screen of Available Balance 
User was thrown with the validation error both on the Stacks add and amount when there were only 5 decimal points to it(which is valid input data)

Expected results:

User should not have validation error thrown as the address and amount are valid.
The address and amount worked as expected prior when user did not included any memo.
Assume this maybe due to some cache issues which could lead to the validation error upon inputting memo and going back and forth between the Preview and Actual screen mode

**Comment by Eshwari007** [comment]
CC :@hstove @andresgalante

**Comment by hstove** [comment]
Thanks @Eshwari007 ! Any chance you could provide a screen recording? I think I follow the issue but it would be really helpful if I could visualize the flow

**Comment by hstove** [comment]
@Eshwari007 thanks, this is definitely helpful!

**Comment by kyranjamie** [comment]
Thanks for reporting @Eshwari007— I will look into this

**Comment by markmhx** [comment]
@kyranjamie any luck figuring out what's going on here?

**Comment by kyranjamie** [comment]
I haven't looked into this yet.

**Comment by kyranjamie** [comment]
Fixed in https://github.com/blockstack/stacks-wallet/pull/821

**Comment by Eshwari007** [comment]
@kyranjamie Guess this 'old 'bug of mine also got fixed together.Test passed
