### ISSUE TITLE
Upgrade `@zondax/ledger-blockstack` in preparation for `0.13.0` (testnet and multi-sig support)

### ISSUE THREAD

**Issue by kyranjamie** [hirosystems/stacks-wallet#814]
This issue is for the second half of the upgrade plan defined in https://github.com/blockstack/stacks-wallet/issues/798

> 2. On Stacks Ledger app release in Ledger Live store
Release a new version of the wallet that only supports the new version and above.

A new version of the wallet needs to be created which 
1. Uses the latest Ledger app version
2. Passes a chain mode depending on network
3. Prohibits versions of the Stacks app < `0.13`

**Update 2021-5-25:** In starting this task I installed `0.13.0` on my Nano S on which I've installed firmware 2.0. The app doesn't open anymore. ~~@markmhx can you validate this? Requires installing the latest firmware (via LL) and the the [build here](https://github.com/Zondax/ledger-blockstack/releases/tag/v0.13.0).~~

See conversation with Jaun from Slack, this task is pending a working build for 2.0

> **Kyran**
Running https://github.com/Zondax/ledger-blockstack/releases/tag/v0.13.0 on a Nano S with firmware version 2.0, it freezes when trying to open Stacks app. Is this expected? In that the build has to target a given firmware version, or could 2.0 be incompatible with 0.13?
**Juan**
it is incompatible with our build, because CI is still using SDK 1.6, however, if rebuilt (as ledger did on their side) it should be fine. anyway, to avoid any complications, I will open an issue about upgrading to SDK2.0 and we will do it asap

**Update 2021-6-22**: 
To prepare for the Ledger app update, we need to test the latest build with the wallet. We only have a build for firmware 1.6 (and I upgraded to 2). As https://github.com/Zondax/ledger-blockstack/issues/65 hasn't been addressed, it makes sense to just buy a new one, as it probably has old firmware, and use to this test the upgrade path. cc/ @andresgalante @markmhx

**Comment by timstackblock** [comment]
We have run into a blocker for testing @kyranjamie when attempting to run the new zondax file I am using the instructions we have been using up to this point in the read me file for testing and intall. The latest release v0.2.0 does not have a ./installer_s.sh file so I took the previous release of the zondax installer and this is what I am getting. When using v0.13.0

<img width="568" alt="Screen Shot 2021-07-19 at 2 24 49 PM" src="https://user-images.githubusercontent.com/49165468/126208898-181abb60-2802-4bba-b000-94c5ae7ca424.png">


It keeps throwing this error for line 7, I have seen this before in a previous build.

<img width="1009" alt="Screen Shot 2021-07-19 at 2 31 13 PM" src="https://user-images.githubusercontent.com/49165468/126210671-2b88b44b-5d8c-4783-abc7-344db5685471.png">

**Comment by timstackblock** [comment]
:shipit:
