### ISSUE TITLE
Fix event metrics delivery

### ISSUE THREAD

**Issue by markmhx** [hirosystems/stacks-wallet#928]
The app should trigger a "View [route]" event every time the user opens a new view with a "time to render" parameter that measures the complete paint time in milliseconds.

Additionally the app should trigger events for the following actions:

- Start active session: When user opens any view for first time or after 4 hours since the last view open
- Copy Secret Key to clipboard: When user selects option to copy Secret Key to clipboard
- Copy address to clipboard: When user selects option to copy address to clipboard
- Submit valid Secret Key: When user submits a valid Secret Key for sign in
- Submit invalid Secret Key: When user submits a valid Secret Key for sign in
- Submit valid password: When user submits a valid password for sign up or in
- Submit invalid password: When user submits a valid password for sign up or in
- Enter amount for send: When user enters any value into amount input for send form
- Select maximum amount for send: When user selects maximum value for send form
- Enter recipient for send: When user enters any value into recipient input for send form
- Enter memo for send: When user enters any value into memo input for send form
- Change network: When user selects network
- Add network: When user submits new network
- Sign out: When user signs out manually
- View transaction: When user selects transaction for view in Explorer
- Broadcast transaction: When user submits transaction for broadcast
- Transaction state change: When outbound or inbound transaction is recognized with new state (attributes: type => inbound|outbound, state => pending|microblock|anchor|failed, time_since_last_state => time in milliseconds)
- Toggle transaction signing inputs: When user opens or closed view of transaction signing inputs (attributes: action => open|close)
- View API error (attributes: code => number, message => string)

All events should have these default properties:

- Anonymous ID for user by account
- Authenticated (boolean): Indicating whether the user has authenticated or not upon triggering event
- Route (string): Path of current view upon triggering event
- UTM parameters (string): All available UTM parameters as stored in session from last availability in GET parameters
- User agent (string)
- Version (string)
- Timestamp
- Selected network (string)
- Has STX (boolean): Whether current account has positive STX balance
- Has FT (boolean): Whether current account has positive non-STX FT balance
- Has NFT (boolean): Whether current account has one or more NFTs

**Comment by beguene** [comment]
Implemented events:

copy_address_to_clipboard
reset_wallet (equivalent of signout)
broadcast_transaction
select_maximum_amount_for_send
view_transaction
copy_secret_key_to_clipboard
submit_invalid_secret_key
submit_valid_secret_key
submit_valid_password
submit_invalid_password

**Comment by timstackblock** [comment]
I cant assign this issue to myself

**Comment by andresgalante** [comment]
I just assigned it to you and change the permissions of the repo

**Comment by timstackblock** [comment]
> Implemented events:
> 
> copy_address_to_clipboard reset_wallet (equivalent of signout) broadcast_transaction select_maximum_amount_for_send view_transaction copy_secret_key_to_clipboard submit_invalid_secret_key submit_valid_secret_key submit_valid_password submit_invalid_password



I am only testing agains the events listed as implemented above, I have created this issue for the missing events
https://github.com/hirosystems/stacks-wallet/issues/977

**Comment by Eshwari007** [comment]
@beguene Moving this back to development as @timstackblock found the missing events

**Comment by beguene** [comment]
@Eshwari007 This is fixed now. https://github.com/hirosystems/stacks-wallet/issues/977#issuecomment-966339834

**Comment by andresgalante** [comment]
@beguene please have a final look and merge this PR

**Comment by markmhx** [comment]
See https://github.com/hirosystems/stacks-wallet/pull/960#issuecomment-1044544196
