### ISSUE TITLE
[4.5.3] Bug: <describe issue>

### ISSUE THREAD

**Issue by Metatrons9** [hirosystems/stacks-wallet#929]
Bug found testing Hiro Wallet build undefined, 4.5.3.

Hi, I'm am trying to connect to Ledger Nano X and my ledger doesn't not give me any results when I search for stacks / STX / Blockstack ... so I was trying to get the Hiro wallet to get my coins off binance as they are closing down for the province i live in in Canada. Any help on this?  I downloaded and opened your desktop option and then opened the window that says connect your ledger and I went through the motions. It recognizes that its connected to my ledger but then I can't open stacks.

Thank you for your help!

Metatron

**Comment by kyranjamie** [comment]
Please try with latest version, reopen if problem persists
