### ISSUE TITLE
how to upgrade to newer stacks wallet when original was secured by trezor

### ISSUE THREAD

**Issue by hingst101** [hirosystems/stacks-wallet#949]
I wrote a question yesterday where my STX balance was invalid and I couldn't send the balance to the new Hiro wallet.  I was told to upgrade to a more current Stacks wallet.  I can't upgrade to the Hiro wallet because my Stacks V1 wallet was secured by Trezor and the Hiro wallet doesn't support Trezor.  Is there a link you can provide where I can download a more current version of the Stacks wallet so that I can access my STX and send it to the Hiro wallet?  Thanks.

**Comment by kyranjamie** [comment]
You can read more information here about Trezor support. Unfortunately, Trezor doesn't support the new way in which Stacks works. [Methods to recover your funds are described here.](https://www.hiro.so/questions/how-can-i-use-my-trezor-device-with-the-stacks-wallet)
