### ISSUE TITLE
SEGEMENT BUG : The following events are not triggering on the desktop app

### ISSUE THREAD

**Issue by timstackblock** [hirosystems/stacks-wallet#977]
submit_invalid_secret_key
submit_valid_secret_key

**Comment by beguene** [comment]
@timstackblock Have you have a chance to look at this ? This should work fine now.

**Comment by timstackblock** [comment]
Yes the secret key events still do not work

Please see this video https://somup.com/crXXIy0VBR

<img width="1171" alt="Screen Shot 2021-11-11 at 8 34 06 AM" src="https://user-images.githubusercontent.com/49165468/141307104-8425a5dd-40f4-432a-a7b1-48bb3b5cb40d.png">

**Comment by beguene** [comment]
Thanks @timstackblock, I will check

**Comment by beguene** [comment]
@timstackblock It was working when you create the wallet but not on sign in. I just fixed it.
