### ISSUE TITLE
[4.6.0] Bug: <describe issue>

### ISSUE THREAD

**Issue by christianwiens** [hirosystems/stacks-wallet#980]
I'm trying to send stx out from my Hiro wallet.

SP217NHGNMH5T5HB8WYWZ48ZAK5PNGGRYMG4KQ6Y2

Initially I got this error:

{
  "error": "transaction rejected",
  "reason": "NotEnoughFunds",
  "reason_data": {
    "actual": "0x00000000000000000000000000000000",
    "expected": "0x00000000000000000000000005f6fa40"
  },
  "txid": "fe00ebccad41cabf2c796221c2f49b94d73ec7c1815ce17c3fce93ad4db885f1"
}

Now it will let me send the stx out but it won't let me. It initially said it went through but then the stx supposedly returned to my wallet.

My wallet clearly shows stx in it. Why can't I send my funds out.

Bug found testing Hiro Wallet build undefined, 4.6.0.

**Comment by markmhx** [comment]
Is this issue still outstanding?
