### ISSUE TITLE
[4.6.0] Bug: Funds transfer wallet to wallet due to lost seed

### ISSUE THREAD

**Issue by toddbeckmann** [hirosystems/stacks-wallet#982]
Bug found testing Hiro Wallet build undefined, 4.6.0.
[4.6.0] Bug: <describe issue>Transfer of assets from wallet (I lost the seed) to new wallet. First two attempts to send 262.92782 STX failed with an error. I then turned off my VPN (to just use my local ISP instead of Kapersky VPN, connected through Mexico; Note: the receiving machine remained on Kaspersky VPN connected via Canada at all times), and sent 262.92782 STX for a third time. All three Txids went through with the amount changed to 62.92782 STX each, leaving 74.00054 STX in my original wallet (the one with the lost seed). 
Finally I sent 73.92854 STX to the new wallet and received the same error again (screen shot .jpg attached). I did not attempt to send this transaction again (Try Again Button) as it had a Txid (#4 below) which, if it actually failed, should not have been generated. Plus the fact that the previous failures also went through. So, I waited for it to go through, which it did a few minutes later.
Txid1: 0xe3dfc2e9611c55b39f1c73955ef48e8d4ff1e999803470d89aaf6d93b1945b5f 
Txid2: 0x16e6ea4cf9ec50d6b146214256a04f0a8c4a55dbba5e1ace5aeb9de25ac3df16 
Txid 3: 0xeb9ea85e1cfe07a58eb3c6b2a06ab92a349fdaf67b557e10abab7a2b6db31af1 
Txid 4: 0x473abd0e5bd7a3db1ca23f071b9a3e16baa1be57ecc9d026f0a0b2a1f90d3f

I have all of my STX (less three extra transaction fees than necessary) so I was not unduly harmed by this problem. I would think that this kind of issue is not the way you want the wallet to work. I hope I have provided enough information for you to decipher what happened here. I am going to proceed to staking my STX now. Hopefully, I will not have this problem doing the required transactions for staking.

Sending PC Lenovo Think Pad: 
Device ID: B71B37DC-6665-48AA-9432-3BDB306793E
Product ID: 00325-81505-32384-AAOEM
Processor: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz   2.59 GHz
Installed RAM: 16.0 GB (15.7 GB usable)
Windows specs
Edition: Windows 10 Home; Version: 21H1; Installed: 9/10/20; 
OS build: 19043.1348; Serial number PF1DC29N; 
Experience: Windows Feature Experience Pack 120.2212.3920.0

Receiving PC Lenovo ThinkCentre
Device ID: 77ABB1F5-CB3C-4EA2-8E68-9621BBFC52C7
Product ID: 00325-81500-05610-AAOEM
Processor: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
Installed RAM: 48.0 GB (47.8 GB usable)
Windows specs
Edition: Windows 10 Home; Version: 20H2; Installed: 12/‎19/‎2020; 
OS build: 19042.1348; Serial number MJ0A6PZL; 
Experience: Windows Feature Experience Pack 120.2212.3920.0

![github error report screen capture 2021-11-15_12-24-34](https://user-images.githubusercontent.com/41970872/141834054-ff4e6dd3-bb6a-48d5-b70b-c3ea23fedf55.jpg)
d1

**Comment by markmhx** [comment]
@toddbeckmann we believe this was related to an API issue that has since been resolved. Please let us know if you still see this and we'll reopen.
