### ISSUE TITLE
[4.2.0] Bug: Ledger crashing on Stacks app start

### ISSUE THREAD

**Issue by gnewfield** [hirosystems/stacks-wallet#987]
When I open the Stacks app on my Ledger device, the manager crashes. Picture below. If I try to proceed with creating my wallet from the Stacks app, I get stuck at step 3 with no way to proceed (also pictured below). On the device itself, this can also cause the app to quit and return me to the dashboard. To be clear, the manager works fine until I open the Stacks app on the device, so I'm fairly certain that this is the root cause. I see that the 2.0.0 firmware update for Ledger was released less than a month ago. Could there be some incompatibility? Any insight appreciated!

I followed the steps [here](https://www.hiro.so/questions/how-can-i-use-my-ledger-device-with-stacks-wallet) to set up my Ledger Nano X with the Hiro Desktop Wallet. Here are my system details:

- Ledger device: Nano X (Firmware Version 2.0.0)
- Stacks Wallet: Version 4.2.0
- Operating system: macOS Big Sur Version 11.5.2

<img width="1009" alt="Screen Shot 2021-11-21 at 2 18 06 AM" src="https://user-images.githubusercontent.com/18626088/142753319-f6b0bc65-1536-47c7-847d-3f87519daccf.png">
<img width="592" alt="Screen Shot 2021-11-21 at 2 18 39 AM" src="https://user-images.githubusercontent.com/18626088/142753343-56a334e1-3faa-4fd7-aede-aa5337bcb7c1.png">

**Comment by gnewfield** [comment]
A few more details I learned from debugging:

- If the Hiro Wallet Desktop application is closed, then no error is thrown in Ledger Live manager. Instead, if I open the Stacks app on my Nano, the app will wait a couple of seconds before sending me back to the device dashboard.
- When I open the Hiro Wallet and do the same, then Ledger Live throws the above error.
- Finally, if I close the Hiro Wallet application on my Desktop, the Ledger Live manager is able to resume its normal functionality, displaying which apps are installed and how much memory I have allocated to them.
- I opened an issue with Ledger to investigate from their side, but the above observations lead me to believe that there's something going on with the compatibility between the Ledger Live and Hiro Wallet versions.

**Comment by kyranjamie** [comment]
Thanks for the report @gnewfield

Ledger devices can only really be accessed by one piece of software at a time. If you're using LL then try and use the Hiro Wallet, it likely won't work. That is to say, you can't use both at once.

If you have only one open at a time, does it work as expected?

**Comment by gnewfield** [comment]
Thank you for clarifying @kyranjamie

Here are the steps I've followed:

1. Open Hiro Wallet application on my laptop
2. "Accept terms of service"
3. "I already have a wallet"
4. "Continue with Ledger"
5. Connect Ledger device, enter PIN, and open Stacks app on device
6. Press both buttons on device to clear "Pending review" alert
7. Check marks appear within Hiro Wallet next to items 1 and 2 (pictured above). Item 3 "Confirm address" remains to be completed
8. "Continue"
9. Loading wheel spins on the "Continue" button within Hiro Wallet. Nothing appears on the device

How do I complete the "Confirm address" step?

**Comment by kyranjamie** [comment]
Indeed, when you press the _Confirm address_ step you should see it appear on your Ledger. 

> P.S. On the main page of the app, there's a message that says "⚠️ Please check our status page for known issues if you’re experiencing any difficulties. Check status↗" Clicking this link leads to "Page Not Found" on the stacks.co site.

Are you running the the latest version of the Hiro Wallet, `v4.6.0`? We've since removed this warning.

**Comment by gnewfield** [comment]
That did the trick!

Just as a note for future users, the new Hiro Wallet is a separate application from the old Stacks Wallet. My issue was that I had downloaded and installed the new application, thinking that it would replace the old one. Instead, however, both were in my Applications folder and even had the same icon. Make sure you open Hiro Wallet, and go ahead and delete the old Stacks Wallet application.

Thank you for your support @kyranjamie!
