### ISSUE TITLE
[4.1.1] Bug: <describe issue>

### ISSUE THREAD

**Issue by clevemcmillan** [hirosystems/stacks-wallet#990]
Cant locate my balance. Money. Zero. Any tips. Transfered over from blockstack some months back and have no clue with all this mess where it may be. 
thanks 
c

Bug found testing Stacks Wallet build undefined, 4.1.1.

**Comment by markmhx** [comment]
Are you accessing the desktop wallet with a 24-word key or Ledger device?

**Comment by kyranjamie** [comment]
This is quite an old version of the wallet, too. Make sure to upgrade.
