### ISSUE TITLE
[4.6.0] Bug: revoked delegation - still locked 3 weeks later

### ISSUE THREAD

**Issue by CryptoBismol** [hirosystems/stacks-wallet#993]
https://explorer.stacks.co/txid/0x1aea8b8e2d53c8558f6b0b6655f6a5e86b193b4cd29b266bce4c940447f60c51?utm_source=stacks-wallet&chain=mainnet

this is the explorer. I revoked on November 9th.  still locked.  any help would be appreciated.

<img width="1041" alt="Screen Shot 2021-12-01 at 10 37 33 AM" src="https://user-images.githubusercontent.com/95373119/144285114-5d69cd0e-ad73-4197-afa4-6865b6a4855b.png">

**Comment by markmhx** [comment]
Revoking doesn't mean that Stacking itself stops, just that the pool to which you've revoked cannot initiate Stacking _again_ with your funds.

If there is already Stacking in progress for any length of time, you'll need to wait until it completes in full for your STX to become available / unlocked again.

**Comment by CryptoBismol** [comment]
my lord, I am locked and not earning any longer? for the duration? I think i did maximum months lock. only 40% done  Is it possible to get funds back in?  How is an app with such a bad UI and not allow access to funds like this useable in the long run?

**Comment by kyranjamie** [comment]
![image](https://user-images.githubusercontent.com/1618764/144574571-55ecb3cc-098e-41b9-8b83-daea6413ac59.png)

We have a warning in place users must agree to before they are allowed to pool.
