### ISSUE TITLE
[4.3.1] Bug: <describe issue>

### ISSUE THREAD

**Issue by nyonmong** [hirosystems/stacks-wallet#997]
I am having an issue on the HIRO stacks wallet connecting to my Ledger Nano X. I am trying to send coins to my wallet and when I get to the part where it says "request ledger address" I click on it and nothing on my ledger shows up. It worked before obviously because I was able to send my STX tokens to the wallet when I created the wallet for the first time. However, now it won't show an address to send my tokens to and I can't do anything with the tokens I have in there already because they are locked up and I need to deposit more to start staking. Apparently you need some free to make this transaction possible which I was unaware of. My computer is a Windows 10 pro 64 bit. Can someone please tell me what I need to do to solve this problem?

Thank you

nyonmong

Bug found testing Stacks Wallet build undefined, 4.3.1.

**Comment by kyranjamie** [comment]
You're using a very outdated version of the wallet. Can you upgrade and try again?

If this doesn't fix, please reopen the issue.

**Comment by nyonmong** [comment]
Are you referring to the wallet on my Ledger Nano X or the Hiro wallet?
Please tell me which one.

Thank you

**Comment by nyonmong** [comment]
I tried uninstalling the STX app on my Ledger Nano X and reinstalling it
and it still will not show my address. Everything looks to be updated. I
don’t have any update buttons on my Ledger Nano X to update the firmware or
anything either. Please tell me how to proceed.

**Comment by kyranjamie** [comment]
The Hiro Wallet is out of date. Please make sure to download the latest at hiro.so/wallet-desktop. Make sure to use Hiro Wallet and not Stacks Wallet

**Comment by nyonmong** [comment]
Ok I got it! Thank you. I hit the update button before but it looked like
what I did initially to install the Hiro wallet which wasn’t done that long
ago that’s why I didn’t understand I needed to just download it again.
Anyway, I downloaded it again and it worked. Thank you for your help!
