### ISSUE TITLE
[4.6.0] Bug: <describe issue>My password is not accepted by HiroWallet

### ISSUE THREAD

**Issue by apocaliptico** [hirosystems/stacks-wallet#998]
Bug found testing Hiro Wallet build undefined, 4.6.0.

**Comment by kyranjamie** [comment]
Can you share details of the system you're running?

**Comment by apocaliptico** [comment]
Sure, windows ten, this computer is a hybrid, my son put it together with components from amazon; by the way it appears Hiro requires the input of a node, something I am not familiar with and when I type Coinbase they want a URL, which I do not know

**Comment by kyranjamie** [comment]
Can you share a screenshot of this?
